version: '3.3'
services:
  buildsection:
    image: build-agent:latest
    build:
      context: .
      dockerfile: ./Docker/build-agent/Dockerfile
  testsection:
    image: test-agent:latest
    build:
      context: .
      dockerfile: ./Docker/test-agent/Dockerfile
    depends_on:
      - buildsection
  deploysection:
    image: build-agent:latest
    build:
      context: .
      dockerfile: ./Docker/build-agent/Dockerfile
